local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc="Browse project files"})
vim.keymap.set('n', '<leader>sg', builtin.git_files, {desc="Browse project git files."})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, {desc="Search project files."})
vim.keymap.set('n', '<leader>ig', builtin.live_grep, {desc="Incremental grep search project files."})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {desc="Search buffers."})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {desc="Search vimdocs"})
